
 # Programación para el Análisis de Datos
 ### Tarea 1
 ### Presentado por: Kevin Alejandro Cardenas Quintero
 ### Grupo 39
 ### Código: 203008069
 ### Presentado a: Felipe Alexander Pipicano Guzman
 ### Universidad Nacional Abierta y a Distancia - UNAD
 ### 03 de Marzo 2024

## Ejercicio 2

## Definiciones

### Arreglos:

En el contexto de la programación, un arreglo es una estructura de datos que contiene una colección de elementos del mismo tipo, organizados en una secuencia indexada. Los arreglos pueden ser unidimensionales (vectores), bidimensionales (matrices) o multidimensionales. En algunos lenguajes de programación, como Python, los arreglos pueden ser implementados utilizando listas, tuplas o arreglos específicos de bibliotecas como NumPy.

### Vectores:

Un "vector" es una entidad matemática que representa una cantidad con magnitud y dirección. En el contexto de la programación y la matemática computacional, un vector se refiere comúnmente a una secuencia ordenada de elementos numéricos, que puede ser unidimensional.

Un vector es una colección ordenada de números, conocidos como componentes o elementos del vector. Puede ser representado como:

 $$
\mathbf{v} = \begin{pmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{pmatrix}
 $$

donde  $$ v_1, v_2, \ldots, v_n  $$ son los elementos del vector. Los vectores son una forma específica de arreglos unidimensionales que se utilizan para representar cantidades direccionales o magnitudes en álgebra lineal y geometría. En Python, los vectores se pueden representar utilizando la biblioteca NumPy.

### Matrices:

Una matriz es una disposición rectangular de números, símbolos o expresiones, dispuestos en filas y columnas. Las matrices se utilizan en una amplia variedad de aplicaciones, desde la resolución de sistemas de ecuaciones lineales hasta el análisis de datos en la ciencia de datos y la ingeniería. Las matrices pueden sumarse, restarse y multiplicarse entre sí, y se pueden multiplicar por escalares (números). La multiplicación de matrices tiene propiedades específicas, como la propiedad asociativa, distributiva y la existencia de la identidad y la inversa para algunas matrices.

Una matriz puede ser representada como:

 $$
\mathbf{A} = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1m} \\
a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nm}
\end{pmatrix}
 $$

donde  $ a_{ij}  $ representa el elemento en la fila  $ i  $ y la columna  $ j  $ de la matriz.

## Operaciones con Vectores y Matrices

### Suma de Vectores y Matrices

La suma de dos vectores o matrices del mismo tamaño se realiza sumando componente por componente:

 $$
\mathbf{v} + \mathbf{w} = \begin{pmatrix}
v_1 + w_1 \\
v_2 + w_2 \\
\vdots \\
v_n + w_n
\end{pmatrix}
 $$

 $$
\mathbf{A} + \mathbf{B} = \begin{pmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1m} + b_{1m} \\
a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2m} + b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} + b_{n1} & a_{n2} + b_{n2} & \cdots & a_{nm} + b_{nm}
\end{pmatrix}
 $$

### Producto Punto (Producto Escalar)

El producto punto entre dos vectores de la misma dimensión se calcula multiplicando componente por componente y sumando los resultados:

 $$
\mathbf{v} \cdot \mathbf{w} = v_1w_1 + v_2w_2 + \ldots + v_nw_n
 $$

### Producto Cruz (Producto Vectorial)

El producto cruz entre dos vectores tridimensionales produce un vector que es perpendicular a los vectores originales:

 $$
\mathbf{v} \times \mathbf{w} = \begin{pmatrix}
v_2w_3 - v_3w_2 \\
v_3w_1 - v_1w_3 \\
v_1w_2 - v_2w_1
\end{pmatrix}
 $$

### Matriz Transpuesta

La matriz transpuesta se obtiene intercambiando filas por columnas:

 $$
\mathbf{A}^T = \begin{pmatrix}
a_{11} & a_{21} & \cdots & a_{n1} \\
a_{12} & a_{22} & \cdots & a_{n2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1m} & a_{2m} & \cdots & a_{nm}
\end{pmatrix}
$$






### Multiplicación de Matrices

La multiplicación de matrices es una operación fundamental en álgebra lineal que combina los elementos de dos matrices para producir una tercera matriz. Para que dos matrices puedan multiplicarse, el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz.

Sean$ \mathbf{A} $ y$ \mathbf{B} $ dos matrices, donde$ \mathbf{A} $ es una matriz de tamaño$ n \times m $ y$ \mathbf{B} $ es una matriz de tamaño$ m \times p $. El producto de$ \mathbf{A} $ y$ \mathbf{B} $, denotado como$ \mathbf{A} \times \mathbf{B} $, es una matriz$ n \times p $ donde cada entrada$ c_{ij} $ se calcula como la suma de los productos de los elementos de la fila $ i $ de$ \mathbf{A} $ por los elementos correspondientes de la columna$ j $ de $ \mathbf{B} $.

En general, la entrada $ c_{ij} $ de la matriz resultante se calcula como:

$$ c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + \ldots + a_{im}b_{mj} $$

donde $ a_{ik} $ representa el elemento en la fila$ i $ y la columna$ k $ de la matriz$ \mathbf{A} $, y$ b_{kj} $ representa el elemento en la fila$ k $ y la columna $ j $ de la matriz$ \mathbf{B} $.

La matriz resultante $ \mathbf{C} $ será de tamaño $n$.

### Descripción del ejercicio:

Desarrolle códigos para ejecutar las siguientes tareas:

• Construya la siguiente matriz como un arreglo de numpy:

 $$
\mathbf{A} = \begin{pmatrix}
13 & 1\\
14 & 1\\
15 & 1\\
16 & 1\\
17 & 1\\
18 & 1
\end{pmatrix}
 $$
   
• Construya el siguiente vector como arreglo de numpy:

 $$
\mathbf{b} = \begin{pmatrix}
16 \\
24 \\
45 \\
57 \\
75 \\
102
\end{pmatrix}
 $$

• Calcule el siguiente vector x, usando operaciones de matrices (dot, transpose, inv) de numpy.linalg:

$$ 𝑥 = (𝐴T𝐴)(-1) 𝐴T𝑏 $$

y calcule $ ‖𝐴𝑥 − 𝑏‖$ utilizando la función numpy.linalg.norm.

• Solucione el siguiente sistema de ecuaciones, mediante la función numpy.linalg.solve (de ser necesario, investigue la función en la documentación de numpy):

$$(𝐴T𝐴)𝑥 = 𝐴T𝑏$$

y calcule $‖𝐴𝑥 − 𝑏‖$ utilizando la función numpy.linalg.norm.

• Solucione el siguiente sistema de ecuaciones, mediante la función numpy.linalg.lstsq (de ser necesario, investigue la función en la documentación de numpy):
$$𝐴𝑥 = 𝑏$$
y calcule $‖𝐴𝑥 − 𝑏‖$ utilizando la función numpy.linalg.norm.

• Compare todos los resultados obtenidos y anexe una discusión en el análisis de resultados.

### Paso 1
• Construya la siguiente matriz como un arreglo de numpy:

 $$
\mathbf{A} = \begin{pmatrix}
13 & 1\\
14 & 1\\
15 & 1\\
16 & 1\\
17 & 1\\
18 & 1
\end{pmatrix}
 $$

In [4]:
import numpy as np

In [5]:
A = np.array([[13, 1], [14, 1],[15, 1],[16, 1],[17, 1],[18, 1]])

In [6]:
A

array([[13,  1],
       [14,  1],
       [15,  1],
       [16,  1],
       [17,  1],
       [18,  1]])

### Paso 2

• Construya el siguiente vector como arreglo de numpy:

 $$
\mathbf{b} = \begin{pmatrix}
16 \\
24 \\
45 \\
57 \\
75 \\
102
\end{pmatrix}
 $$

In [7]:
b = np.array([[16], [24], [45], [57], [75], [102]])

In [8]:
b

array([[ 16],
       [ 24],
       [ 45],
       [ 57],
       [ 75],
       [102]])

### Paso 3

• Calcule el siguiente vector x, usando operaciones de matrices (dot, transpose, inv) de numpy.linalg:

$$𝑥 = ((𝐴^T𝐴)^-1𝐴^T𝑏$$

y calcule $‖𝐴𝑥 − 𝑏‖$ utilizando la función numpy.linalg.norm.

In [9]:
A_transpose = np.transpose(A)
A_transpose_A = np.dot(A_transpose, A)
A_transpose_A_inv = np.linalg.inv(A_transpose_A)
A_transpose_b = np.dot(A_transpose, b)

x1 = np.dot(A_transpose_A_inv, A_transpose_b)

In [10]:
x1

array([[  17.        ],
       [-210.33333333]])

In [11]:
Ax1 = np.dot(A, x1)
diferencia = Ax1 - b
valor = np.linalg.norm(diferencia)

In [12]:
valor

10.83205120618128

### Paso 4
Solucione el siguiente sistema de ecuaciones, mediante la función numpy.linalg.solve (de ser necesario, investigue la función en la documentación de numpy):

$$(𝐴T𝐴)𝑥 = 𝐴T𝑏$$

y calcule $‖𝐴𝑥 − 𝑏‖ $utilizando la función numpy.linalg.norm.


In [13]:
x2 = np.linalg.solve(A_transpose_A, A_transpose_b)

In [14]:
x2

array([[  17.        ],
       [-210.33333333]])

In [15]:
Ax2 = np.dot(A, x2)
diferencia = Ax2 - b
valor2 = np.linalg.norm(diferencia)

In [16]:
valor2

10.832051206181271

### Paso 5

Solucione el siguiente sistema de ecuaciones, mediante la función numpy.linalg.lstsq (de ser necesario, investigue la función en la documentación de numpy):

$$𝐴𝑥 = 𝑏$$

y calcule $‖𝐴𝑥 − 𝑏‖$ utilizando la función numpy.linalg.norm.


In [17]:
x3, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

In [18]:
x3

array([[  17.        ],
       [-210.33333333]])

In [19]:
Ax3 = np.dot(A, x3)
diferencia = Ax3 - b
valor3 = np.linalg.norm(diferencia)

In [20]:
valor3

10.832051206181276

## Análisis de resultados


1. **Matrices resultantes**: En los tres procesos, la matriz resultanteisma estructura. Parece que independientemente del proceso, la matriz resultante es:
   ```
   [[  17.        ],
    [-210.33333333]]
   ```
   Esto sugiere que el proceso aplicado a la matriz \( A \) y al vector \( b \) produce consistentemente la misma solución.

2. **Valor de error \( x \)**: El valor de error en los tres casos es muy similar, con ligeras variaciones en la precisión debido a la forma en que se han calculado o redondeado los números. Sin embargo, la diferencia es muy pequeña, lo que sugiere que los tres procesos están produciendo resultados muy cercanos  efectivos en este contexto particular.

## Conclusiones

Dado que los resultados son consistentes en términos de la matriz resultante y el valor de error, podemos inferir que los tres procesos aplicados a la matriz \(A\) y al vector \(b\) son equivalentes o muy similares en términos de su efecto en el resultado. La ligera variación en el valor de error puede ser atribuible a diferencias en el método de cálculo o redondeo en los diferentes procesos.




## Referencias

Thakur, A. (2016). Python: Real-World Data Science. Packt Publishing. (pp. 491 - 508).
